name: Workflow to send HTTP Requests when meged into the primary branch

on:
  push:
    branches:
      - main
jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Check if the push is a merge
        id: check_merge
        run: |
          if [[ $(git log -1 --pretty=%P) =~ " " ]]; then
            echo "merge=true" >> $GITHUB_ENV
          else
            echo "merge=false" >> $GITHUB_ENV
          fi

      - name: Send HTTP request
        if: env.merge == 'true'
        run: |
          curl -X POST "https://example.com/your-api-endpoint" \
            -H "Content-Type: application/json" \
